name: agroai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi
    - uvicorn
    - pydantic
    - torch
    - tensorflow
    - transformers
    - langchain
    - crewai
    - yolov8
    - pinecone-client
    - weaviate-client
    - python-dotenv
    - pandas
    - scikit-learn
    - jupyter
    - black
    - flake8
    - pytest
    - docker
    - boto3
    - azure-storage-blob
    - google-cloud-storage
